#!/usr/bin/env node
import path from 'node:path';
import { readdir, readFile, writeFile } from 'node:fs/promises';
import { exists, repoRoot } from './lib/fs-utils.mjs';

const stocksDir = path.join(repoRoot, 'stocks');
const outputPath = path.join(repoRoot, 'index-data.js');

function extractLastUpdated(html) {
  const dataMatch = html.match(/data-last-updated="([^"]+)"/i);
  if (dataMatch?.[1]) return dataMatch[1];
  const timeMatch = html.match(/<time[^>]*datetime="([^"]*)"[^>]*>([\s\S]*?)<\/time>/i);
  if (timeMatch?.[1]) return timeMatch[1];
  if (timeMatch?.[2]) return timeMatch[2].replace(/<[^>]+>/g, '').trim();
  const textMatch = html.match(/Last updated:\s*([^<\n]+)/i);
  return textMatch?.[1]?.trim() || 'unknown';
}

async function readProfile(dir, ticker) {
  const profilePath = path.join(dir, 'profile.json');
  if (!(await exists(profilePath))) return { ticker, company: ticker };
  try {
    const profile = JSON.parse(await readFile(profilePath, 'utf8'));
    return {
      ticker: String(profile.ticker || ticker).toUpperCase(),
      company: profile.company || ticker
    };
  } catch {
    return { ticker, company: ticker };
  }
}

const entries = await readdir(stocksDir, { withFileTypes: true });
const summaries = [];

for (const entry of entries) {
  if (!entry.isDirectory() || entry.name === '_TEMPLATE' || entry.name.startsWith('.')) continue;
  const ticker = entry.name.toUpperCase();
  const dir = path.join(stocksDir, entry.name);
  const profile = await readProfile(dir, ticker);
  const summaryPath = path.join(dir, 'summary.html');
  const hasSummary = await exists(summaryPath);
  let lastUpdated = 'missing';
  if (hasSummary) {
    const html = await readFile(summaryPath, 'utf8');
    lastUpdated = extractLastUpdated(html);
  }
  summaries.push({
    ticker: profile.ticker,
    company: profile.company,
    lastUpdated,
    hasSummary,
    summaryPath: `stocks/${ticker}/summary.html`
  });
}

const generated = [
  '// Generated by tools/build-index.mjs. Do not commit stock-specific directory data.',
  `window.STOCK_INDEX_GENERATED_AT = ${JSON.stringify(new Date().toISOString())};`,
  `window.STOCK_SUMMARIES = ${JSON.stringify(summaries, null, 2)};`,
  ''
].join('\n');

await writeFile(outputPath, generated, 'utf8');
console.log(JSON.stringify({ outputPath, count: summaries.length }, null, 2));
